services:
  - type: web
    name: telarespadel
    dockerfile: Dockerfile
    dockerfilePath: ./Dockerfile
    plan: free

  - type: mysql
    name: telarespadel-db
    plan: free
    mysqlVersion: 5.7
    databaseName: torneos_telares
    user: telarespadel_user


